-- MySQL Script generated by MySQL Workbench
-- Tue Sep  6 17:00:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema buildingestateadvance
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema buildingestateadvance
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `buildingestateadvance` DEFAULT CHARACTER SET utf8 ;
USE `buildingestateadvance` ;

-- -----------------------------------------------------
-- Table `buildingestateadvance`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buildingestateadvance`.`user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `createdby` VARCHAR(255) NULL DEFAULT NULL,
  `createddate` DATETIME NULL DEFAULT NULL,
  `modifiedby` VARCHAR(255) NULL DEFAULT NULL,
  `modifieddate` DATETIME NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `fullname` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `status` INT(11) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_sb8bbouer5wak8vyiiy4pf2bx` (`username` ASC) VISIBLE,
  UNIQUE INDEX `UK_ob8kqyqqgmefl0aco34akdtpe` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `buildingestateadvance`.`building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buildingestateadvance`.`building` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `createdby` VARCHAR(255) NULL DEFAULT NULL,
  `createddate` DATETIME NULL DEFAULT NULL,
  `modifiedby` VARCHAR(255) NULL DEFAULT NULL,
  `modifieddate` DATETIME NULL DEFAULT NULL,
  `brokeragefee` VARCHAR(255) NULL DEFAULT NULL,
  `carfee` VARCHAR(255) NULL DEFAULT NULL,
  `decorationtime` VARCHAR(255) NULL DEFAULT NULL,
  `deposit` VARCHAR(255) NULL DEFAULT NULL,
  `direction` VARCHAR(255) NULL DEFAULT NULL,
  `districtcode` VARCHAR(255) NOT NULL,
  `electricityfee` VARCHAR(255) NULL DEFAULT NULL,
  `floorarea` INT(11) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `level` VARCHAR(255) NULL DEFAULT NULL,
  `linkofbuilding` VARCHAR(255) NULL DEFAULT NULL,
  `managername` VARCHAR(255) NULL DEFAULT NULL,
  `managerphone` VARCHAR(255) NULL DEFAULT NULL,
  `map` VARCHAR(255) NULL DEFAULT NULL,
  `motorbikefee` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `note` VARCHAR(255) NULL DEFAULT NULL,
  `numberofbasement` INT(11) NULL DEFAULT NULL,
  `overtimefee` VARCHAR(255) NULL DEFAULT NULL,
  `payment` VARCHAR(255) NULL DEFAULT NULL,
  `rentprice` INT(11) NULL DEFAULT NULL,
  `rentpricedescription` VARCHAR(255) NULL DEFAULT NULL,
  `renttime` VARCHAR(255) NULL DEFAULT NULL,
  `servicefee` VARCHAR(255) NULL DEFAULT NULL,
  `street` VARCHAR(255) NOT NULL,
  `structure` VARCHAR(255) NULL DEFAULT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  `ward` VARCHAR(255) NOT NULL,
  `waterfee` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `buildingestateadvance`.`assignmentbuilding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buildingestateadvance`.`assignmentbuilding` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `createdby` VARCHAR(255) NULL DEFAULT NULL,
  `createddate` DATETIME NULL DEFAULT NULL,
  `modifiedby` VARCHAR(255) NULL DEFAULT NULL,
  `modifieddate` DATETIME NULL DEFAULT NULL,
  `buildingid` BIGINT(20) NULL DEFAULT NULL,
  `staffid` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKkk3mdegrmfcdlsxqds1m6q238` (`buildingid` ASC) VISIBLE,
  INDEX `FKf4ibbod44h32ao1o6pb4yq98p` (`staffid` ASC) VISIBLE,
  CONSTRAINT `FKf4ibbod44h32ao1o6pb4yq98p`
    FOREIGN KEY (`staffid`)
    REFERENCES `buildingestateadvance`.`user` (`id`),
  CONSTRAINT `FKkk3mdegrmfcdlsxqds1m6q238`
    FOREIGN KEY (`buildingid`)
    REFERENCES `buildingestateadvance`.`building` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `buildingestateadvance`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buildingestateadvance`.`customer` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `createdby` VARCHAR(255) NULL DEFAULT NULL,
  `createddate` DATETIME NULL DEFAULT NULL,
  `modifiedby` VARCHAR(255) NULL DEFAULT NULL,
  `modifieddate` DATETIME NULL DEFAULT NULL,
  `companyname` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `fullname` VARCHAR(255) NOT NULL,
  `need` VARCHAR(255) NULL DEFAULT NULL,
  `note` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_dwk6cx0afu8bs9o4t536v1j5v` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `buildingestateadvance`.`assignmentcustomer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buildingestateadvance`.`assignmentcustomer` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `createdby` VARCHAR(255) NULL DEFAULT NULL,
  `createddate` DATETIME NULL DEFAULT NULL,
  `modifiedby` VARCHAR(255) NULL DEFAULT NULL,
  `modifieddate` DATETIME NULL DEFAULT NULL,
  `customerid` BIGINT(20) NULL DEFAULT NULL,
  `staffid` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK4sygo3a6twd6tkay7em8f1lgg` (`customerid` ASC) VISIBLE,
  INDEX `FKco26n95l1hpuq1suv0briljor` (`staffid` ASC) VISIBLE,
  CONSTRAINT `FK4sygo3a6twd6tkay7em8f1lgg`
    FOREIGN KEY (`customerid`)
    REFERENCES `buildingestateadvance`.`customer` (`id`),
  CONSTRAINT `FKco26n95l1hpuq1suv0briljor`
    FOREIGN KEY (`staffid`)
    REFERENCES `buildingestateadvance`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `buildingestateadvance`.`rentarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buildingestateadvance`.`rentarea` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `createdby` VARCHAR(255) NULL DEFAULT NULL,
  `createddate` DATETIME NULL DEFAULT NULL,
  `modifiedby` VARCHAR(255) NULL DEFAULT NULL,
  `modifieddate` DATETIME NULL DEFAULT NULL,
  `value` INT(11) NULL DEFAULT NULL,
  `buildingid` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKqhqoxlvm1iblaew5s0v8n3ut4` (`buildingid` ASC) VISIBLE,
  CONSTRAINT `FKqhqoxlvm1iblaew5s0v8n3ut4`
    FOREIGN KEY (`buildingid`)
    REFERENCES `buildingestateadvance`.`building` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `buildingestateadvance`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buildingestateadvance`.`role` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `createdby` VARCHAR(255) NULL DEFAULT NULL,
  `createddate` DATETIME NULL DEFAULT NULL,
  `modifiedby` VARCHAR(255) NULL DEFAULT NULL,
  `modifieddate` DATETIME NULL DEFAULT NULL,
  `code` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_c36say97xydpmgigg38qv5l2p` (`code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `buildingestateadvance`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buildingestateadvance`.`transaction` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `createdby` VARCHAR(255) NULL DEFAULT NULL,
  `createddate` DATETIME NULL DEFAULT NULL,
  `modifiedby` VARCHAR(255) NULL DEFAULT NULL,
  `modifieddate` DATETIME NULL DEFAULT NULL,
  `note` VARCHAR(255) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `customerid` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKldobv9jeuxje0fjqnhrw6e23v` (`customerid` ASC) VISIBLE,
  CONSTRAINT `FKldobv9jeuxje0fjqnhrw6e23v`
    FOREIGN KEY (`customerid`)
    REFERENCES `buildingestateadvance`.`customer` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `buildingestateadvance`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buildingestateadvance`.`user_role` (
  `userid` BIGINT(20) NOT NULL,
  `roleid` BIGINT(20) NOT NULL,
  INDEX `FKbo5ik0bthje7hum554xb17ry6` (`roleid` ASC) VISIBLE,
  INDEX `FKd0xwi6psywvnj59btfns0alnm` (`userid` ASC) VISIBLE,
  CONSTRAINT `FKbo5ik0bthje7hum554xb17ry6`
    FOREIGN KEY (`roleid`)
    REFERENCES `buildingestateadvance`.`role` (`id`),
  CONSTRAINT `FKd0xwi6psywvnj59btfns0alnm`
    FOREIGN KEY (`userid`)
    REFERENCES `buildingestateadvance`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
